### ISSUE TITLE
share the deploy of freepbx

### ISSUE THREAD

**Issue by extprom** [escomputers/k8s-freepbx#12]
HI,
It would be great to share the deploy of freepbx
Thx

**Comment by escomputers** [comment]
Hi,
unfortunately, due to work commitments, I wasn't able to make progress on the project. I made it public specifically to encourage collaboration. However, by taking inspiration from the [freepbx-docker repository,](https://github.com/escomputers/freepbx-docker) which contains the container image, it should be possible to create the K8S Deployment without too much difficulty.
